name: Run Login Script and Setup Cron Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # 每三小时运行一次，可以根据需求调整时间
  push:
    branches:
      - main

jobs:
  login_and_install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: Create accounts.json from environment variable
        run: echo "$ACCOUNTS_JSON" > accounts.json
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}  # 从GitHub Secrets中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyppeteer aiofiles requests
          pip install --upgrade pyppeteer

      - name: 处理每个账号
        run: |
          python -c "
import json
import subprocess

with open('accounts.json') as f:
    accounts = json.load(f)

for account in accounts:
    # 设置环境变量
    account_env = {
        'TELEGRAM_BOT_TOKEN': '${{ secrets.TELEGRAM_BOT_TOKEN }}',
        'TELEGRAM_CHAT_ID': '${{ secrets.TELEGRAM_CHAT_ID }}',
        'ACCOUNT_INFO': json.dumps(account)
    }

    # 运行登录脚本
    subprocess.run(['python', 'login_script.py'], env={**os.environ, **account_env})
    
    # 执行安装脚本
    subprocess.run(['bash', '-c', 'bash <(curl -s https://raw.githubusercontent.com/ansoncloud8/am-serv00-socks5/main/install-socks5.sh)'])
    subprocess.run(['bash', '-c', 'bash <(curl -s https://raw.githubusercontent.com/ansoncloud8/am-serv00-nezha/main/install-dashboard.sh)'])
    subprocess.run(['bash', '-c', 'bash <(curl -s https://raw.githubusercontent.com/ansoncloud8/am-serv00-nezha/main/install-agent.sh)'])
          "
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
